#!/system/bin/sh
# CGI: save config from POST
MODDIR=/data/adb/modules/smsforward
CONFIG="$MODDIR/config"
STATEDIR="$MODDIR/state"
mkdir -p "$STATEDIR"

echo "Content-Type: text/html; charset=utf-8"
echo ""

# Read body
len=${CONTENT_LENGTH:-0}
body=""
if [ "$REQUEST_METHOD" = "POST" ] && [ "$len" -gt 0 ] 2>/dev/null; then
  body=$(dd bs=1 count="$len" 2>/dev/null)
elif [ "$REQUEST_METHOD" = "POST" ]; then
  body=$(cat)
fi

get_field() {
  # $1=name from body a=b&c=d
  printf '%s' "$body" | tr '&' '\n' | grep "^$1=" | head -1 | sed "s/^$1=//"
}

udecode() {
  # basic percent-decode
  printf '%s' "$1" | sed 's/+/ /g' | sed \
    -e 's/%0A/\n/g' -e 's/%0a/\n/g' \
    -e 's/%0D//g' -e 's/%0d//g' \
    -e 's/%20/ /g' -e 's/%21/!/g' -e 's/%22/"/g' -e 's/%23/#/g' \
    -e 's/%24/$/g' -e 's/%25/%/g' -e 's/%26/\&/g' -e "s/%27/'/g" \
    -e 's/%28/(/g' -e 's/%29/)/g' -e 's/%2B/+/g' -e 's/%2b/+/g' \
    -e 's/%2C/,/g' -e 's/%2c/,/g' -e 's/%2F/\//g' -e 's/%2f/\//g' \
    -e 's/%3A/:/g' -e 's/%3a/:/g' -e 's/%3B/;/g' -e 's/%3b/;/g' \
    -e 's/%3C/</g' -e 's/%3c/</g' -e 's/%3D/=/g' -e 's/%3d/=/g' \
    -e 's/%3E/>/g' -e 's/%3e/>/g' -e 's/%3F/?/g' -e 's/%3f/?/g' \
    -e 's/%40/@/g' -e 's/%5B/[/g' -e 's/%5b/[/g' -e 's/%5D/]/g' -e 's/%5d/]/g' \
    -e 's/%7B/{/g' -e 's/%7b/{/g' -e 's/%7D/}/g' -e 's/%7d/}/g'
}

# shell-escape for double-quoted values in config
qesc() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\$/\\$/g; s/`/\\`/g'
}

DEVICE_NAME=$(udecode "$(get_field DEVICE_NAME)")
SIM_NUMBER=$(udecode "$(get_field SIM_NUMBER)")
POLL_INTERVAL=$(udecode "$(get_field POLL_INTERVAL)")
BARK_KEY=$(udecode "$(get_field BARK_KEY)")
BARK_SERVER=$(udecode "$(get_field BARK_SERVER)")
BARK_ICON=$(udecode "$(get_field BARK_ICON)")
BARK_SOUND=$(udecode "$(get_field BARK_SOUND)")
SMTP_HOST=$(udecode "$(get_field SMTP_HOST)")
SMTP_PORT=$(udecode "$(get_field SMTP_PORT)")
SMTP_ENCRYPTION=$(udecode "$(get_field SMTP_ENCRYPTION)")
SMTP_USER=$(udecode "$(get_field SMTP_USER)")
SMTP_PASS=$(udecode "$(get_field SMTP_PASS)")
MAIL_FROM=$(udecode "$(get_field MAIL_FROM)")
MAIL_TO=$(udecode "$(get_field MAIL_TO)")
TELEGRAM_BOT_TOKEN=$(udecode "$(get_field TELEGRAM_BOT_TOKEN)")
TELEGRAM_CHAT_ID=$(udecode "$(get_field TELEGRAM_CHAT_ID)")
WEBHOOK_URL=$(udecode "$(get_field WEBHOOK_URL)")

[ -n "$POLL_INTERVAL" ] || POLL_INTERVAL=5
[ -n "$DEVICE_NAME" ] || DEVICE_NAME=Card1
[ -n "$BARK_SERVER" ] || BARK_SERVER=https://api.day.app
[ -n "$SMTP_PORT" ] || SMTP_PORT=587
[ -n "$SMTP_ENCRYPTION" ] || SMTP_ENCRYPTION=starttls
[ -n "$BARK_SOUND" ] || BARK_SOUND=glass
[ -n "$BARK_ICON" ] || BARK_ICON=https://upload.wikimedia.org/wikipedia/commons/8/85/IMessage_icon.png

cat > "$CONFIG" <<CFG
# Generated by SMS Forward WebUI
DEVICE_NAME="$(qesc "$DEVICE_NAME")"
SIM_NUMBER="$(qesc "$SIM_NUMBER")"
POLL_INTERVAL=$POLL_INTERVAL

BARK_KEY="$(qesc "$BARK_KEY")"
BARK_SERVER="$(qesc "$BARK_SERVER")"
BARK_ICON="$(qesc "$BARK_ICON")"
BARK_SOUND="$(qesc "$BARK_SOUND")"

SMTP_HOST="$(qesc "$SMTP_HOST")"
SMTP_PORT=$SMTP_PORT
SMTP_ENCRYPTION="$(qesc "$SMTP_ENCRYPTION")"
SMTP_USER="$(qesc "$SMTP_USER")"
SMTP_PASS="$(qesc "$SMTP_PASS")"
MAIL_FROM="$(qesc "$MAIL_FROM")"
MAIL_TO="$(qesc "$MAIL_TO")"

TELEGRAM_BOT_TOKEN="$(qesc "$TELEGRAM_BOT_TOKEN")"
TELEGRAM_CHAT_ID="$(qesc "$TELEGRAM_CHAT_ID")"
WEBHOOK_URL="$(qesc "$WEBHOOK_URL")"
CFG

echo "<!DOCTYPE html><html><head><meta charset=utf-8><meta name=viewport content=\"width=device-width,initial-scale=1\"><meta http-equiv=refresh content=\"1;url=/\"><title>Saved</title>
<style>body{font-family:sans-serif;background:#0b1220;color:#e8eefc;display:flex;min-height:100vh;align-items:center;justify-content:center}</style></head>
<body><p>已保存 ✅ 正在返回…</p></body></html>"
